apiVersion: v1
kind: Service
metadata:
  name: helpchain-service
  namespace: helpchain
  labels:
    app: helpchain
    component: web
spec:
  selector:
    app: helpchain
    component: web
  ports:
  - port: 80
    targetPort: 5000
    name: http
  type: ClusterIP