services:
  - type: web
    name: helpchain
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "set -e; export FLASK_DEBUG=1; export PYTHONUNBUFFERED=1; export SQLALCHEMY_ECHO=1; pwd; ls -la; ls -la migrations || true; ls -la migrations/versions || true; flask --app run:app db current --directory migrations || true; flask --app run:app db heads --directory migrations || true; flask --app run:app db upgrade --directory migrations -v; gunicorn run:app --bind 0.0.0.0:$PORT"
    region: frankfurt
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: PRODUCTION
        value: true
    databases:
      - name: helpchain-db
        databaseName: helpchain
        user: helpchain_user
        region: frankfurt
