services:
  - type: web
    name: helpchain
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -c \"from run import app; app.app_context().push(); from backend.helpchain_backend.src.extensions import db; print('DB_URL=', db.engine.url)\" && flask --app run:app db current --directory backend/migrations && flask --app run:app db heads --directory backend/migrations && flask --app run:app db upgrade --directory backend/migrations && flask --app run:app db current --directory backend/migrations && gunicorn run:app --bind 0.0.0.0:$PORT"
    region: frankfurt
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: PRODUCTION
        value: true
    databases:
      - name: helpchain-db
        databaseName: helpchain
        user: helpchain_user
        region: frankfurt
