services:
  - type: web
    name: helpchain
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "set -euo pipefail; set -x; pwd; ls -la; ls -la migrations || true; python -V; export PYTHONUNBUFFERED=1; export FLASK_DEBUG=1; flask --app run:app db upgrade --directory migrations -v 2>&1; gunicorn run:app --bind 0.0.0.0:$PORT"
    region: frankfurt
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: PRODUCTION
        value: true
    databases:
      - name: helpchain-db
        databaseName: helpchain
        user: helpchain_user
        region: frankfurt
