line-length = 150
target-version = "py311"

extend-exclude = [
  "**/backup*.py",
  "**/*.backup*.py",
  "**/appy.backup*.py",
  "backend/backups/*"
]

[lint]
select = ["E", "F", "I", "B", "UP"]
ignore = ["E203", "E501", "E402", "F841", "B008", "F401", "B007", "E722", "UP038", "B904", "F811"]

[format]
quote-style = "double"
indent-style = "space"
