[pytest]
norecursedirs = HelpChain.bg helpchain_backend .venv venv venv_old htmlcov old_db .git __pycache__
testpaths =
    tests
    .
python_files = test_*.py
pythonpath = .
filterwarnings =
    ignore:'locked_cached_property' is deprecated and will be removed in Flask 2.4.:DeprecationWarning:flask_babel
    ignore:datetime\.datetime\.utcfromtimestamp\(\) is deprecated:DeprecationWarning:dateutil.tz.tz
    ignore::gevent.monkey.MonkeyPatchWarning
    ignore::UserWarning:flask_caching
    ignore::DeprecationWarning:flask_caching
