"""Add Feedback model

Revision ID: 11470b83273b
Revises: e20fdef9ec54
Create Date: 2025-09-10 08:58:08.028122

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "11470b83273b"
down_revision = "e20fdef9ec54"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feedback")
    # ### end Alembic commands ###
