"""baseline_initial_schema

Revision ID: 2086039276b7
Revises: 
Create Date: 2026-03-17 12:44:43.714572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2086039276b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('requirement_type', sa.String(length=50), nullable=True),
    sa.Column('requirement_value', sa.String(length=50), nullable=True),
    sa.Column('rarity', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('admin_username', sa.String(length=120), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("ix_admin_audit_events_action", 'admin_audit_events', ['action'], unique=False)
    op.create_index("ix_admin_audit_events_admin_user_id", 'admin_audit_events', ['admin_user_id'], unique=False)
    op.create_index("ix_admin_audit_events_admin_username", 'admin_audit_events', ['admin_username'], unique=False)
    op.create_index("ix_admin_audit_events_created_at", 'admin_audit_events', ['created_at'], unique=False)
    op.create_index("ix_admin_audit_events_target_id", 'admin_audit_events', ['target_id'], unique=False)
    op.create_index("ix_admin_audit_events_target_type", 'admin_audit_events', ['target_type'], unique=False)
    op.create_table('admin_login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("ix_admin_login_attempts_created_at", 'admin_login_attempts', ['created_at'], unique=False)
    op.create_index("ix_admin_login_attempts_ip", 'admin_login_attempts', ['ip'], unique=False)
    op.create_index("ix_admin_login_attempts_username", 'admin_login_attempts', ['username'], unique=False)
    op.create_table('admin_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('chat_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_send_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('email_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('ua', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("ix_email_send_events_created_at", 'email_send_events', ['created_at'], unique=False)
    op.create_index("ix_email_send_events_email_hash", 'email_send_events', ['email_hash'], unique=False)
    op.create_index('ix_email_send_events_hash_purpose_created', 'email_send_events', ['email_hash', 'purpose', 'created_at'], unique=False)
    op.create_index("ix_email_send_events_purpose", 'email_send_events', ['purpose'], unique=False)
    op.create_table('guardrail_counters',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('magic_link_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('used_ip', sa.String(length=64), nullable=True),
    sa.Column('used_ua', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("ix_magic_link_tokens_email", 'magic_link_tokens', ['email'], unique=False)
    op.create_index("ix_magic_link_tokens_expires_at", 'magic_link_tokens', ['expires_at'], unique=False)
    op.create_index("ix_magic_link_tokens_purpose", 'magic_link_tokens', ['purpose'], unique=False)
    op.create_index("ix_magic_link_tokens_request_id", 'magic_link_tokens', ['request_id'], unique=False)
    op.create_index("ix_magic_link_tokens_token_hash", 'magic_link_tokens', ['token_hash'], unique=True)
    op.create_index("ix_magic_link_tokens_used_at", 'magic_link_tokens', ['used_at'], unique=False)
    op.create_table('notification_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint', name='uq_notification_subscriptions_endpoint')
    )
    op.create_table('notification_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.String(length=5), nullable=True),
    sa.Column('variables', sa.Text(), nullable=True),
    sa.Column('send_delay', sa.Integer(), nullable=True),
    sa.Column('expiry_hours', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('codename', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codename'),
    sa.UniqueConstraint('name')
    )
    op.create_table('professional_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('profession', sa.String(length=120), nullable=False),
    sa.Column('organization', sa.String(length=160), nullable=True),
    sa.Column('availability', sa.String(length=80), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("ix_professional_leads_city", 'professional_leads', ['city'], unique=False)
    op.create_index("ix_professional_leads_email", 'professional_leads', ['email'], unique=False)
    op.create_index("ix_professional_leads_profession", 'professional_leads', ['profession'], unique=False)
    op.create_index("ix_professional_leads_status", 'professional_leads', ['status'], unique=False)
    op.create_table('request_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('time_to_assign', sa.Integer(), nullable=True),
    sa.Column('time_to_complete', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("ix_request_metrics_request_id", 'request_metrics', ['request_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('security_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('ua_hash', sa.String(length=64), nullable=True),
    sa.Column('route', sa.String(length=128), nullable=True),
    sa.Column('method', sa.String(length=8), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_security_events_created_at', 'security_events', ['created_at'], unique=False)
    op.create_index('ix_security_events_event_type_created_at', 'security_events', ['event_type', 'created_at'], unique=False)
    op.create_table('structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index("ix_structures_status", 'structures', ['status'], unique=False)
    op.create_table('ui_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'locale', name='uq_ui_translations_key_locale')
    )
    op.create_index("ix_ui_translations_created_at", 'ui_translations', ['created_at'], unique=False)
    op.create_index("ix_ui_translations_key", 'ui_translations', ['key'], unique=False)
    op.create_index("ix_ui_translations_locale", 'ui_translations', ['locale'], unique=False)
    op.create_index('ix_ui_translations_locale_key', 'ui_translations', ['locale', 'key'], unique=False)
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('structure_id', sa.Integer(), nullable=True),
    sa.Column('totp_secret', sa.String(length=32), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.Column('mfa_enrolled_at', sa.DateTime(), nullable=True),
    sa.Column('backup_codes_hashes', sa.Text(), nullable=True),
    sa.Column('backup_codes_generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['structure_id'], ['structures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index("ix_admin_users_structure_id", 'admin_users', ['structure_id'], unique=False)
    op.create_table('intervenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('legacy_volunteer_id', sa.Integer(), nullable=True),
    sa.Column('actor_type', sa.String(length=50), server_default='volunteer', nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['structure_id'], ['structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("ix_intervenants_actor_type", 'intervenants', ['actor_type'], unique=False)
    op.create_index("ix_intervenants_created_at", 'intervenants', ['created_at'], unique=False)
    op.create_index("ix_intervenants_legacy_volunteer_id", 'intervenants', ['legacy_volunteer_id'], unique=False)
    op.create_index("ix_intervenants_structure_id", 'intervenants', ['structure_id'], unique=False)
    op.create_table('notification_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='5', nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('structure_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['structure_id'], ['structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("ix_notification_jobs_channel", 'notification_jobs', ['channel'], unique=False)
    op.create_index("ix_notification_jobs_created_at", 'notification_jobs', ['created_at'], unique=False)
    op.create_index("ix_notification_jobs_event_type", 'notification_jobs', ['event_type'], unique=False)
    op.create_index("ix_notification_jobs_next_retry_at", 'notification_jobs', ['next_retry_at'], unique=False)
    op.create_index("ix_notification_jobs_recipient", 'notification_jobs', ['recipient'], unique=False)
    op.create_index("ix_notification_jobs_status", 'notification_jobs', ['status'], unique=False)
    op.create_index('ix_notification_jobs_status_next', 'notification_jobs', ['status', 'next_retry_at'], unique=False)
    op.create_index("ix_notification_jobs_structure_id", 'notification_jobs', ['structure_id'], unique=False)
    op.create_table('notification_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('recipient_type', sa.String(length=50), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('recipient_email', sa.String(length=200), nullable=True),
    sa.Column('personalization_data', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('last_attempt', sa.DateTime(), nullable=True),
    sa.Column('next_retry', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['notification_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('structure_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['structure_id'], ['structures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('structure_id', 'code', name='uq_structure_services_structure_code'),
    sa.UniqueConstraint('structure_id', 'name', name='uq_structure_services_structure_name')
    )
    op.create_index('ix_structure_services_structure_active', 'structure_services', ['structure_id', 'is_active'], unique=False)
    op.create_index("ix_structure_services_structure_id", 'structure_services', ['structure_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('structure_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['structure_id'], ['structures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index("ix_users_structure_id", 'users', ['structure_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=True),
    sa.Column('push_enabled', sa.Boolean(), nullable=True),
    sa.Column('sms_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('p256dh', sa.String(), nullable=False),
    sa.Column('auth', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('replaced_by_jti', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("ix_refresh_tokens_jti", 'refresh_tokens', ['jti'], unique=True)
    op.create_index("ix_refresh_tokens_user_id", 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('location_text', sa.String(length=500), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('source_channel', sa.String(length=100), nullable=True),
    sa.Column('assigned_volunteer_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('structure_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('owned_at', sa.DateTime(), nullable=True),
    sa.Column('requester_token_hash', sa.String(length=128), nullable=True),
    sa.Column('requester_token_created_at', sa.DateTime(), nullable=True),
    sa.Column('risk_score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('risk_level', sa.String(length=20), server_default='standard', nullable=False),
    sa.Column('risk_signals', sa.Text(), nullable=True),
    sa.Column('risk_last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['structure_services.id'], ),
    sa.ForeignKeyConstraint(['structure_id'], ['structures.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("ix_requests_category", 'requests', ['category'], unique=False)
    op.create_index("ix_requests_deleted_at", 'requests', ['deleted_at'], unique=False)
    op.create_index("ix_requests_is_archived", 'requests', ['is_archived'], unique=False)
    op.create_index("ix_requests_owner_id", 'requests', ['owner_id'], unique=False)
    op.create_index("ix_requests_requester_token_hash", 'requests', ['requester_token_hash'], unique=False)
    op.create_index("ix_requests_service_id", 'requests', ['service_id'], unique=False)
    op.create_table('social_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.Integer(), nullable=False),
    sa.Column('need_type', sa.String(length=64), nullable=False),
    sa.Column('urgency', sa.String(length=16), nullable=False),
    sa.Column('person_ref', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['structure_id'], ['structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("ix_social_requests_assigned_to_user_id", 'social_requests', ['assigned_to_user_id'], unique=False)
    op.create_index("ix_social_requests_created_at", 'social_requests', ['created_at'], unique=False)
    op.create_index('ix_social_requests_status_urgency', 'social_requests', ['status', 'urgency'], unique=False)
    op.create_index('ix_social_requests_struct_status_created', 'social_requests', ['structure_id', 'status', 'created_at'], unique=False)
    op.create_index("ix_social_requests_structure_id", 'social_requests', ['structure_id'], unique=False)
    op.create_table('ui_locale_locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('is_locked', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('locked_by_admin_user_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['locked_by_admin_user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("ix_ui_locale_locks_created_at", 'ui_locale_locks', ['created_at'], unique=False)
    op.create_index("ix_ui_locale_locks_locale", 'ui_locale_locks', ['locale'], unique=True)
    op.create_index("ix_ui_locale_locks_locked_at", 'ui_locale_locks', ['locked_at'], unique=False)
    op.create_index("ix_ui_locale_locks_locked_by_admin_user_id", 'ui_locale_locks', ['locked_by_admin_user_id'], unique=False)
    op.create_table('ui_translation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('translation_id', sa.Integer(), nullable=True),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), server_default='human', nullable=False),
    sa.Column('actor_admin_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('old_text', sa.Text(), nullable=True),
    sa.Column('new_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_admin_user_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['translation_id'], ['ui_translations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("ix_ui_translation_events_action", 'ui_translation_events', ['action'], unique=False)
    op.create_index("ix_ui_translation_events_actor_admin_user_id", 'ui_translation_events', ['actor_admin_user_id'], unique=False)
    op.create_index("ix_ui_translation_events_created_at", 'ui_translation_events', ['created_at'], unique=False)
    op.create_index("ix_ui_translation_events_key", 'ui_translation_events', ['key'], unique=False)
    op.create_index("ix_ui_translation_events_locale", 'ui_translation_events', ['locale'], unique=False)
    op.create_index('ix_ui_translation_events_locale_key_created_at', 'ui_translation_events', ['locale', 'key', 'created_at'], unique=False)
    op.create_index("ix_ui_translation_events_translation_id", 'ui_translation_events', ['translation_id'], unique=False)
    op.create_table('ui_translation_freeze',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('release_tag', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('activated_by_admin_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activated_by_admin_user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("ix_ui_translation_freeze_activated_at", 'ui_translation_freeze', ['activated_at'], unique=False)
    op.create_index("ix_ui_translation_freeze_activated_by_admin_user_id", 'ui_translation_freeze', ['activated_by_admin_user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('availability', sa.String(length=50), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('volunteer_onboarded', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('achievements', sa.Text(), nullable=True),
    sa.Column('total_tasks_completed', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('streak_days', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('total_hours_volunteered', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('intervenant_id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['intervenant_id'], ['intervenants.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['structure_id'], ['structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("ix_assignments_assigned_at", 'assignments', ['assigned_at'], unique=False)
    op.create_index("ix_assignments_assigned_by_admin_id", 'assignments', ['assigned_by_admin_id'], unique=False)
    op.create_index("ix_assignments_intervenant_id", 'assignments', ['intervenant_id'], unique=False)
    op.create_index("ix_assignments_request_id", 'assignments', ['request_id'], unique=False)
    op.create_index("ix_assignments_status", 'assignments', ['status'], unique=False)
    op.create_index("ix_assignments_structure_id", 'assignments', ['structure_id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.Integer(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_professional_lead_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_professional_lead_id'], ['professional_leads.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['structure_id'], ['structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("ix_cases_assigned_professional_lead_id", 'cases', ['assigned_professional_lead_id'], unique=False)
    op.create_index('ix_cases_coordinates', 'cases', ['latitude', 'longitude'], unique=False)
    op.create_index("ix_cases_created_at", 'cases', ['created_at'], unique=False)
    op.create_index("ix_cases_last_activity_at", 'cases', ['last_activity_at'], unique=False)
    op.create_index("ix_cases_owner_user_id", 'cases', ['owner_user_id'], unique=False)
    op.create_index("ix_cases_priority", 'cases', ['priority'], unique=False)
    op.create_index("ix_cases_request_id", 'cases', ['request_id'], unique=True)
    op.create_index("ix_cases_status", 'cases', ['status'], unique=False)
    op.create_index("ix_cases_structure_id", 'cases', ['structure_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('volunteer_id', 'type', 'request_id', name='uq_notif_vol_type_req')
    )
    op.create_index("ix_notifications_is_read", 'notifications', ['is_read'], unique=False)
    op.create_index("ix_notifications_request_id", 'notifications', ['request_id'], unique=False)
    op.create_index("ix_notifications_type", 'notifications', ['type'], unique=False)
    op.create_index("ix_notifications_volunteer_id", 'notifications', ['volunteer_id'], unique=False)
    op.create_table('request_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('actor_admin_id', sa.Integer(), nullable=True),
    sa.Column('volunteer_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("ix_request_activities_actor_admin_id", 'request_activities', ['actor_admin_id'], unique=False)
    op.create_index("ix_request_activities_request_id", 'request_activities', ['request_id'], unique=False)
    op.create_index("ix_request_activities_volunteer_id", 'request_activities', ['volunteer_id'], unique=False)
    op.create_table('request_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("ix_request_logs_request_id", 'request_logs', ['request_id'], unique=False)
    op.create_table('social_request_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.String(length=255), nullable=True),
    sa.Column('new_value', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['social_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("ix_social_request_events_actor_user_id", 'social_request_events', ['actor_user_id'], unique=False)
    op.create_index("ix_social_request_events_created_at", 'social_request_events', ['created_at'], unique=False)
    op.create_index("ix_social_request_events_request_id", 'social_request_events', ['request_id'], unique=False)
    op.create_table('volunteer_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'volunteer_id', name='uq_volunteer_action_request_volunteer')
    )
    op.create_index("ix_volunteer_actions_action", 'volunteer_actions', ['action'], unique=False)
    op.create_index("ix_volunteer_actions_request_id", 'volunteer_actions', ['request_id'], unique=False)
    op.create_index("ix_volunteer_actions_volunteer_id", 'volunteer_actions', ['volunteer_id'], unique=False)
    op.create_table('volunteer_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('volunteer_id', 'request_id', name='uq_volunteer_request_interest')
    )
    op.create_index("ix_volunteer_interests_request_id", 'volunteer_interests', ['request_id'], unique=False)
    op.create_index("ix_volunteer_interests_status", 'volunteer_interests', ['status'], unique=False)
    op.create_index("ix_volunteer_interests_volunteer_id", 'volunteer_interests', ['volunteer_id'], unique=False)
    op.create_table('volunteer_match_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('volunteer_id', 'request_id', name='uq_vol_req_feedback')
    )
    op.create_index("ix_volunteer_match_feedback_request_id", 'volunteer_match_feedback', ['request_id'], unique=False)
    op.create_index("ix_volunteer_match_feedback_volunteer_id", 'volunteer_match_feedback', ['volunteer_id'], unique=False)
    op.create_table('volunteer_request_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('seen_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('volunteer_id', 'request_id', name='uq_volunteer_request_state')
    )
    op.create_index("ix_volunteer_request_states_notified_at", 'volunteer_request_states', ['notified_at'], unique=False)
    op.create_index("ix_volunteer_request_states_request_id", 'volunteer_request_states', ['request_id'], unique=False)
    op.create_index("ix_volunteer_request_states_volunteer_id", 'volunteer_request_states', ['volunteer_id'], unique=False)
    op.create_table('case_collaborators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['structure_id'], ['structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("ix_case_collaborators_case_id", 'case_collaborators', ['case_id'], unique=False)
    op.create_index("ix_case_collaborators_created_at", 'case_collaborators', ['created_at'], unique=False)
    op.create_index("ix_case_collaborators_role", 'case_collaborators', ['role'], unique=False)
    op.create_index("ix_case_collaborators_structure_id", 'case_collaborators', ['structure_id'], unique=False)
    op.create_table('case_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("ix_case_events_actor_user_id", 'case_events', ['actor_user_id'], unique=False)
    op.create_index("ix_case_events_case_id", 'case_events', ['case_id'], unique=False)
    op.create_index("ix_case_events_created_at", 'case_events', ['created_at'], unique=False)
    op.create_index("ix_case_events_event_type", 'case_events', ['event_type'], unique=False)
    op.create_index("ix_case_events_visibility", 'case_events', ['visibility'], unique=False)
    op.create_table('case_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('participant_type', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('professional_lead_id', sa.Integer(), nullable=True),
    sa.Column('external_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['professional_lead_id'], ['professional_leads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("ix_case_participants_added_at", 'case_participants', ['added_at'], unique=False)
    op.create_index("ix_case_participants_case_id", 'case_participants', ['case_id'], unique=False)
    op.create_index("ix_case_participants_participant_type", 'case_participants', ['participant_type'], unique=False)
    op.create_index("ix_case_participants_professional_lead_id", 'case_participants', ['professional_lead_id'], unique=False)
    op.create_index("ix_case_participants_role", 'case_participants', ['role'], unique=False)
    op.create_index("ix_case_participants_status", 'case_participants', ['status'], unique=False)
    op.create_index("ix_case_participants_user_id", 'case_participants', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_case_participants_user_id", table_name='case_participants')
    op.drop_index("ix_case_participants_status", table_name='case_participants')
    op.drop_index("ix_case_participants_role", table_name='case_participants')
    op.drop_index("ix_case_participants_professional_lead_id", table_name='case_participants')
    op.drop_index("ix_case_participants_participant_type", table_name='case_participants')
    op.drop_index("ix_case_participants_case_id", table_name='case_participants')
    op.drop_index("ix_case_participants_added_at", table_name='case_participants')
    op.drop_table('case_participants')
    op.drop_index("ix_case_events_visibility", table_name='case_events')
    op.drop_index("ix_case_events_event_type", table_name='case_events')
    op.drop_index("ix_case_events_created_at", table_name='case_events')
    op.drop_index("ix_case_events_case_id", table_name='case_events')
    op.drop_index("ix_case_events_actor_user_id", table_name='case_events')
    op.drop_table('case_events')
    op.drop_index("ix_case_collaborators_structure_id", table_name='case_collaborators')
    op.drop_index("ix_case_collaborators_role", table_name='case_collaborators')
    op.drop_index("ix_case_collaborators_created_at", table_name='case_collaborators')
    op.drop_index("ix_case_collaborators_case_id", table_name='case_collaborators')
    op.drop_table('case_collaborators')
    op.drop_index("ix_volunteer_request_states_volunteer_id", table_name='volunteer_request_states')
    op.drop_index("ix_volunteer_request_states_request_id", table_name='volunteer_request_states')
    op.drop_index("ix_volunteer_request_states_notified_at", table_name='volunteer_request_states')
    op.drop_table('volunteer_request_states')
    op.drop_index("ix_volunteer_match_feedback_volunteer_id", table_name='volunteer_match_feedback')
    op.drop_index("ix_volunteer_match_feedback_request_id", table_name='volunteer_match_feedback')
    op.drop_table('volunteer_match_feedback')
    op.drop_index("ix_volunteer_interests_volunteer_id", table_name='volunteer_interests')
    op.drop_index("ix_volunteer_interests_status", table_name='volunteer_interests')
    op.drop_index("ix_volunteer_interests_request_id", table_name='volunteer_interests')
    op.drop_table('volunteer_interests')
    op.drop_index("ix_volunteer_actions_volunteer_id", table_name='volunteer_actions')
    op.drop_index("ix_volunteer_actions_request_id", table_name='volunteer_actions')
    op.drop_index("ix_volunteer_actions_action", table_name='volunteer_actions')
    op.drop_table('volunteer_actions')
    op.drop_index("ix_social_request_events_request_id", table_name='social_request_events')
    op.drop_index("ix_social_request_events_created_at", table_name='social_request_events')
    op.drop_index("ix_social_request_events_actor_user_id", table_name='social_request_events')
    op.drop_table('social_request_events')
    op.drop_index("ix_request_logs_request_id", table_name='request_logs')
    op.drop_table('request_logs')
    op.drop_index("ix_request_activities_volunteer_id", table_name='request_activities')
    op.drop_index("ix_request_activities_request_id", table_name='request_activities')
    op.drop_index("ix_request_activities_actor_admin_id", table_name='request_activities')
    op.drop_table('request_activities')
    op.drop_index("ix_notifications_volunteer_id", table_name='notifications')
    op.drop_index("ix_notifications_type", table_name='notifications')
    op.drop_index("ix_notifications_request_id", table_name='notifications')
    op.drop_index("ix_notifications_is_read", table_name='notifications')
    op.drop_table('notifications')
    op.drop_index("ix_cases_structure_id", table_name='cases')
    op.drop_index("ix_cases_status", table_name='cases')
    op.drop_index("ix_cases_request_id", table_name='cases')
    op.drop_index("ix_cases_priority", table_name='cases')
    op.drop_index("ix_cases_owner_user_id", table_name='cases')
    op.drop_index("ix_cases_last_activity_at", table_name='cases')
    op.drop_index("ix_cases_created_at", table_name='cases')
    op.drop_index('ix_cases_coordinates', table_name='cases')
    op.drop_index("ix_cases_assigned_professional_lead_id", table_name='cases')
    op.drop_table('cases')
    op.drop_index("ix_assignments_structure_id", table_name='assignments')
    op.drop_index("ix_assignments_status", table_name='assignments')
    op.drop_index("ix_assignments_request_id", table_name='assignments')
    op.drop_index("ix_assignments_intervenant_id", table_name='assignments')
    op.drop_index("ix_assignments_assigned_by_admin_id", table_name='assignments')
    op.drop_index("ix_assignments_assigned_at", table_name='assignments')
    op.drop_table('assignments')
    op.drop_table('volunteers')
    op.drop_table('user_roles')
    op.drop_index("ix_ui_translation_freeze_activated_by_admin_user_id", table_name='ui_translation_freeze')
    op.drop_index("ix_ui_translation_freeze_activated_at", table_name='ui_translation_freeze')
    op.drop_table('ui_translation_freeze')
    op.drop_index("ix_ui_translation_events_translation_id", table_name='ui_translation_events')
    op.drop_index('ix_ui_translation_events_locale_key_created_at', table_name='ui_translation_events')
    op.drop_index("ix_ui_translation_events_locale", table_name='ui_translation_events')
    op.drop_index("ix_ui_translation_events_key", table_name='ui_translation_events')
    op.drop_index("ix_ui_translation_events_created_at", table_name='ui_translation_events')
    op.drop_index("ix_ui_translation_events_actor_admin_user_id", table_name='ui_translation_events')
    op.drop_index("ix_ui_translation_events_action", table_name='ui_translation_events')
    op.drop_table('ui_translation_events')
    op.drop_index("ix_ui_locale_locks_locked_by_admin_user_id", table_name='ui_locale_locks')
    op.drop_index("ix_ui_locale_locks_locked_at", table_name='ui_locale_locks')
    op.drop_index("ix_ui_locale_locks_locale", table_name='ui_locale_locks')
    op.drop_index("ix_ui_locale_locks_created_at", table_name='ui_locale_locks')
    op.drop_table('ui_locale_locks')
    op.drop_index("ix_social_requests_structure_id", table_name='social_requests')
    op.drop_index('ix_social_requests_struct_status_created', table_name='social_requests')
    op.drop_index('ix_social_requests_status_urgency', table_name='social_requests')
    op.drop_index("ix_social_requests_created_at", table_name='social_requests')
    op.drop_index("ix_social_requests_assigned_to_user_id", table_name='social_requests')
    op.drop_table('social_requests')
    op.drop_index("ix_requests_service_id", table_name='requests')
    op.drop_index("ix_requests_requester_token_hash", table_name='requests')
    op.drop_index("ix_requests_owner_id", table_name='requests')
    op.drop_index("ix_requests_is_archived", table_name='requests')
    op.drop_index("ix_requests_deleted_at", table_name='requests')
    op.drop_index("ix_requests_category", table_name='requests')
    op.drop_table('requests')
    op.drop_index("ix_refresh_tokens_user_id", table_name='refresh_tokens')
    op.drop_index("ix_refresh_tokens_jti", table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('push_subscriptions')
    op.drop_table('notification_preferences')
    op.drop_table('chat_participants')
    op.drop_table('chat_messages')
    op.drop_index("ix_users_structure_id", table_name='users')
    op.drop_table('users')
    op.drop_index("ix_structure_services_structure_id", table_name='structure_services')
    op.drop_index('ix_structure_services_structure_active', table_name='structure_services')
    op.drop_table('structure_services')
    op.drop_table('role_permissions')
    op.drop_table('notification_queue')
    op.drop_index("ix_notification_jobs_structure_id", table_name='notification_jobs')
    op.drop_index('ix_notification_jobs_status_next', table_name='notification_jobs')
    op.drop_index("ix_notification_jobs_status", table_name='notification_jobs')
    op.drop_index("ix_notification_jobs_recipient", table_name='notification_jobs')
    op.drop_index("ix_notification_jobs_next_retry_at", table_name='notification_jobs')
    op.drop_index("ix_notification_jobs_event_type", table_name='notification_jobs')
    op.drop_index("ix_notification_jobs_created_at", table_name='notification_jobs')
    op.drop_index("ix_notification_jobs_channel", table_name='notification_jobs')
    op.drop_table('notification_jobs')
    op.drop_index("ix_intervenants_structure_id", table_name='intervenants')
    op.drop_index("ix_intervenants_legacy_volunteer_id", table_name='intervenants')
    op.drop_index("ix_intervenants_created_at", table_name='intervenants')
    op.drop_index("ix_intervenants_actor_type", table_name='intervenants')
    op.drop_table('intervenants')
    op.drop_index("ix_admin_users_structure_id", table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_index('ix_ui_translations_locale_key', table_name='ui_translations')
    op.drop_index("ix_ui_translations_locale", table_name='ui_translations')
    op.drop_index("ix_ui_translations_key", table_name='ui_translations')
    op.drop_index("ix_ui_translations_created_at", table_name='ui_translations')
    op.drop_table('ui_translations')
    op.drop_index("ix_structures_status", table_name='structures')
    op.drop_table('structures')
    op.drop_index('ix_security_events_event_type_created_at', table_name='security_events')
    op.drop_index('ix_security_events_created_at', table_name='security_events')
    op.drop_table('security_events')
    op.drop_table('roles')
    op.drop_index("ix_request_metrics_request_id", table_name='request_metrics')
    op.drop_table('request_metrics')
    op.drop_index("ix_professional_leads_status", table_name='professional_leads')
    op.drop_index("ix_professional_leads_profession", table_name='professional_leads')
    op.drop_index("ix_professional_leads_email", table_name='professional_leads')
    op.drop_index("ix_professional_leads_city", table_name='professional_leads')
    op.drop_table('professional_leads')
    op.drop_table('permissions')
    op.drop_table('notification_templates')
    op.drop_table('notification_subscriptions')
    op.drop_index("ix_magic_link_tokens_used_at", table_name='magic_link_tokens')
    op.drop_index("ix_magic_link_tokens_token_hash", table_name='magic_link_tokens')
    op.drop_index("ix_magic_link_tokens_request_id", table_name='magic_link_tokens')
    op.drop_index("ix_magic_link_tokens_purpose", table_name='magic_link_tokens')
    op.drop_index("ix_magic_link_tokens_expires_at", table_name='magic_link_tokens')
    op.drop_index("ix_magic_link_tokens_email", table_name='magic_link_tokens')
    op.drop_table('magic_link_tokens')
    op.drop_table('guardrail_counters')
    op.drop_index("ix_email_send_events_purpose", table_name='email_send_events')
    op.drop_index('ix_email_send_events_hash_purpose_created', table_name='email_send_events')
    op.drop_index("ix_email_send_events_email_hash", table_name='email_send_events')
    op.drop_index("ix_email_send_events_created_at", table_name='email_send_events')
    op.drop_table('email_send_events')
    op.drop_table('chat_rooms')
    op.drop_table('admin_roles')
    op.drop_index("ix_admin_login_attempts_username", table_name='admin_login_attempts')
    op.drop_index("ix_admin_login_attempts_ip", table_name='admin_login_attempts')
    op.drop_index("ix_admin_login_attempts_created_at", table_name='admin_login_attempts')
    op.drop_table('admin_login_attempts')
    op.drop_index("ix_admin_audit_events_target_type", table_name='admin_audit_events')
    op.drop_index("ix_admin_audit_events_target_id", table_name='admin_audit_events')
    op.drop_index("ix_admin_audit_events_created_at", table_name='admin_audit_events')
    op.drop_index("ix_admin_audit_events_admin_username", table_name='admin_audit_events')
    op.drop_index("ix_admin_audit_events_admin_user_id", table_name='admin_audit_events')
    op.drop_index("ix_admin_audit_events_action", table_name='admin_audit_events')
    op.drop_table('admin_audit_events')
    op.drop_table('achievements')
    # ### end Alembic commands ###
