"""Generate fresh migrations

Revision ID: bf5882167a72
Revises: 
Create Date: 2025-11-27 18:02:02.703900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bf5882167a72"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "achievements",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(length=255), nullable=True),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column("points_reward", sa.Integer(), nullable=True),
        sa.Column("requirement_type", sa.String(length=64), nullable=True),
        sa.Column("requirement_value", sa.String(length=255), nullable=True),
        sa.Column("rarity", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "admin_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=120), nullable=True),
        sa.Column("password_hash", sa.String(length=128), nullable=True),
        sa.Column(
            "role",
            sa.Enum("SUPER_ADMIN", "ADMIN", "MODERATOR", name="adminrole"),
            nullable=False,
        ),
        sa.Column("twofa_secret", sa.String(length=32), nullable=True),
        sa.Column("backup_codes", sa.Text(), nullable=True),
        sa.Column("two_factor_enabled", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=True),
        sa.Column("locked_until", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "analytics_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("event_category", sa.String(length=100), nullable=True),
        sa.Column("event_action", sa.String(length=100), nullable=True),
        sa.Column("event_label", sa.String(length=255), nullable=True),
        sa.Column("event_value", sa.Integer(), nullable=True),
        sa.Column("user_session", sa.String(length=128), nullable=True),
        sa.Column("user_type", sa.String(length=50), nullable=True),
        sa.Column("user_ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("page_url", sa.String(length=500), nullable=True),
        sa.Column("page_title", sa.String(length=255), nullable=True),
        sa.Column("referrer", sa.String(length=500), nullable=True),
        sa.Column("load_time", sa.Float(), nullable=True),
        sa.Column("screen_resolution", sa.String(length=20), nullable=True),
        sa.Column("device_type", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chat_rooms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chatbot_conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("user_message", sa.Text(), nullable=False),
        sa.Column("bot_response", sa.Text(), nullable=True),
        sa.Column("response_type", sa.String(length=50), nullable=True),
        sa.Column("ai_provider", sa.String(length=50), nullable=True),
        sa.Column("ai_model", sa.String(length=100), nullable=True),
        sa.Column("ai_confidence", sa.Float(), nullable=True),
        sa.Column("ai_tokens_used", sa.Integer(), nullable=True),
        sa.Column("processing_time", sa.Float(), nullable=True),
        sa.Column("user_rating", sa.Integer(), nullable=True),
        sa.Column("user_feedback", sa.Text(), nullable=True),
        sa.Column("page_url", sa.String(length=500), nullable=True),
        sa.Column("user_type", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "failed_emails",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipient", sa.String(length=255), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=False),
        sa.Column("template", sa.String(length=255), nullable=False),
        sa.Column("context", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("failed_emails", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_failed_emails_recipient"), ["recipient"], unique=False
        )

    op.create_table(
        "feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("sentiment_score", sa.Float(), nullable=True),
        sa.Column("sentiment_label", sa.String(length=20), nullable=True),
        sa.Column("sentiment_confidence", sa.Float(), nullable=True),
        sa.Column("ai_processed", sa.Boolean(), nullable=True),
        sa.Column("ai_processing_time", sa.Float(), nullable=True),
        sa.Column("ai_provider", sa.String(length=20), nullable=True),
        sa.Column("user_type", sa.String(length=20), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("page_url", sa.String(length=500), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "feedbacks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("email", sa.String(length=150), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notification_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("html_body", sa.Text(), nullable=True),
        sa.Column("content_type", sa.String(length=20), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "priority",
            sa.Enum("low", "normal", "urgent", name="priorityenum"),
            nullable=True,
        ),
        sa.Column("auto_send", sa.Boolean(), nullable=True),
        sa.Column("send_delay", sa.Integer(), nullable=True),
        sa.Column("expiry_hours", sa.Integer(), nullable=True),
        sa.Column("variables", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "performance_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("metric_type", sa.String(length=100), nullable=False),
        sa.Column("metric_name", sa.String(length=100), nullable=False),
        sa.Column("metric_value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=True),
        sa.Column("endpoint", sa.String(length=255), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("request_size", sa.Integer(), nullable=True),
        sa.Column("response_size", sa.Integer(), nullable=True),
        sa.Column("context_data", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("codename", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("is_system_permission", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codename"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=120), nullable=True),
        sa.Column("location", sa.String(length=100), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("urgency", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_system_role", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "success_stories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_behaviors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("user_type", sa.String(length=50), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("device_info", sa.String(length=100), nullable=True),
        sa.Column("location", sa.String(length=100), nullable=True),
        sa.Column("session_start", sa.DateTime(), nullable=True),
        sa.Column("last_activity", sa.DateTime(), nullable=True),
        sa.Column("total_time_spent", sa.Integer(), nullable=True),
        sa.Column("pages_visited", sa.Integer(), nullable=True),
        sa.Column("entry_page", sa.String(length=500), nullable=True),
        sa.Column("exit_page", sa.String(length=500), nullable=True),
        sa.Column("bounce_rate", sa.Boolean(), nullable=True),
        sa.Column("conversion_action", sa.String(length=100), nullable=True),
        sa.Column("pages_sequence", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=200), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "user", "volunteer", "moderator", "admin", "superadmin", name="roleenum"
            ),
            nullable=False,
        ),
        sa.Column("twofa_secret_encrypted", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_role"), ["role"], unique=False)

    op.create_table(
        "volunteers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=200), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("skills", sa.String(length=500), nullable=True),
        sa.Column("location", sa.String(length=100), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("experience", sa.Integer(), nullable=False),
        sa.Column("total_tasks_completed", sa.Integer(), nullable=False),
        sa.Column("total_hours_volunteered", sa.Float(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("rating_count", sa.Integer(), nullable=False),
        sa.Column("achievements", sa.JSON(), nullable=False),
        sa.Column("badges", sa.JSON(), nullable=False),
        sa.Column("streak_days", sa.Integer(), nullable=False),
        sa.Column("last_activity", sa.DateTime(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("volunteers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_volunteers_location"), ["location"], unique=False
        )

    op.create_table(
        "admin_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("admin_user_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("entity_type", sa.String(length=50), nullable=True),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admin_user_id"],
            ["admin_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "admin_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("admin_user_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("last_activity", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admin_user_id"],
            ["admin_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("target_type", sa.String(), nullable=True),
        sa.Column("target_id", sa.String(), nullable=True),
        sa.Column("outcome", sa.String(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=True),
        sa.Column("sender_type", sa.String(length=20), nullable=False),
        sa.Column("sender_name", sa.String(length=100), nullable=False),
        sa.Column("message_type", sa.String(length=20), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("file_url", sa.String(length=500), nullable=True),
        sa.Column("file_name", sa.String(length=255), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("reply_to_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("edited_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["reply_to_id"],
            ["chat_messages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["chat_rooms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chat_participants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("volunteer_id", sa.Integer(), nullable=True),
        sa.Column("participant_type", sa.String(length=20), nullable=False),
        sa.Column("participant_name", sa.String(length=100), nullable=False),
        sa.Column("joined_at", sa.DateTime(), nullable=True),
        sa.Column("last_seen", sa.DateTime(), nullable=True),
        sa.Column("is_online", sa.Boolean(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["chat_rooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["volunteer_id"],
            ["volunteers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "help_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column(
            "priority",
            sa.Enum("low", "normal", "urgent", name="priorityenum"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("location_text", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("region", sa.String(length=100), nullable=True),
        sa.Column("assigned_volunteer_id", sa.Integer(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("source_channel", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["assigned_volunteer_id"],
            ["volunteers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("help_requests", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_help_requests_assigned_volunteer_id"),
            ["assigned_volunteer_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_help_requests_city"), ["city"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_help_requests_completed_at"), ["completed_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_help_requests_location_text"),
            ["location_text"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_help_requests_region"), ["region"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_help_requests_source_channel"),
            ["source_channel"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_help_requests_status"), ["status"], unique=False
        )

    op.create_table(
        "notification_preferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("system_notifications", sa.Boolean(), nullable=True),
        sa.Column("help_request_notifications", sa.Boolean(), nullable=True),
        sa.Column("volunteer_notifications", sa.Boolean(), nullable=True),
        sa.Column("admin_notifications", sa.Boolean(), nullable=True),
        sa.Column("registration_notifications", sa.Boolean(), nullable=True),
        sa.Column("feedback_notifications", sa.Boolean(), nullable=True),
        sa.Column("marketing_notifications", sa.Boolean(), nullable=True),
        sa.Column("reminder_notifications", sa.Boolean(), nullable=True),
        sa.Column("email_enabled", sa.Boolean(), nullable=True),
        sa.Column("push_enabled", sa.Boolean(), nullable=True),
        sa.Column("app_enabled", sa.Boolean(), nullable=True),
        sa.Column("sms_enabled", sa.Boolean(), nullable=True),
        sa.Column("in_app_enabled", sa.Boolean(), nullable=True),
        sa.Column("frequency", sa.String(length=20), nullable=True),
        sa.Column("quiet_hours_start", sa.Time(), nullable=True),
        sa.Column("quiet_hours_end", sa.Time(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notification_queue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=True),
        sa.Column("recipient_type", sa.String(length=20), nullable=False),
        sa.Column("recipient_id", sa.Integer(), nullable=True),
        sa.Column("recipient_email", sa.String(length=255), nullable=False),
        sa.Column("personalization_data", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=True),
        sa.Column("max_attempts", sa.Integer(), nullable=True),
        sa.Column("last_attempt_at", sa.DateTime(), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(), nullable=True),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.Column("clicked_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("scheduled_for", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["notification_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "push_subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("volunteer_id", sa.Integer(), nullable=False),
        sa.Column("endpoint", sa.String(length=500), nullable=False),
        sa.Column("p256dh_key", sa.String(length=200), nullable=False),
        sa.Column("auth_key", sa.String(length=200), nullable=False),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("notifications_sent", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("last_used", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["volunteer_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("endpoint"),
    )
    op.create_table(
        "role_permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.Column("granted_by", sa.Integer(), nullable=True),
        sa.Column("granted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["granted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("priority", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("location_required", sa.Boolean(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("location_text", sa.String(length=255), nullable=True),
        sa.Column("required_skills", sa.Text(), nullable=True),
        sa.Column("preferred_skills", sa.Text(), nullable=True),
        sa.Column("estimated_hours", sa.Integer(), nullable=True),
        sa.Column("deadline", sa.DateTime(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("assigned_to", sa.Integer(), nullable=True),
        sa.Column("assigned_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["volunteers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["admin_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "two_factor_auth",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("admin_user_id", sa.Integer(), nullable=False),
        sa.Column("session_token", sa.String(length=128), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admin_user_id"],
            ["admin_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_token"),
    )
    op.create_table(
        "user_activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("user_type", sa.String(length=20), nullable=True),
        sa.Column(
            "activity_type",
            sa.Enum(
                "PAGE_VIEW",
                "PAGE_EXIT",
                "SCROLL",
                "TIME_SPENT",
                "BUTTON_CLICK",
                "FORM_SUBMIT",
                "FORM_START",
                "LINK_CLICK",
                "SEARCH_QUERY",
                "HELP_REQUEST_CREATED",
                "HELP_REQUEST_VIEWED",
                "HELP_REQUEST_UPDATED",
                "TASK_VIEWED",
                "TASK_ACCEPTED",
                "TASK_COMPLETED",
                "VOLUNTEER_PROFILE_VIEWED",
                "CHAT_MESSAGE_SENT",
                "CHAT_ROOM_JOINED",
                "VIDEO_CHAT_STARTED",
                "LOGIN",
                "LOGOUT",
                "PASSWORD_RESET",
                "ACHIEVEMENT_UNLOCKED",
                "POINTS_EARNED",
                "LEVEL_UP",
                "ERROR_OCCURRED",
                "PAGE_NOT_FOUND",
                "FORM_VALIDATION_ERROR",
                "REGISTRATION_COMPLETED",
                "HELP_REQUEST_ASSIGNED",
                "TASK_ASSIGNED",
                name="useractivitytypeenum",
            ),
            nullable=False,
        ),
        sa.Column("activity_description", sa.String(length=255), nullable=True),
        sa.Column("activity_data", sa.JSON(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("device_type", sa.String(length=50), nullable=True),
        sa.Column("browser", sa.String(length=100), nullable=True),
        sa.Column("os", sa.String(length=100), nullable=True),
        sa.Column("screen_resolution", sa.String(length=20), nullable=True),
        sa.Column("page_url", sa.String(length=500), nullable=True),
        sa.Column("page_title", sa.String(length=255), nullable=True),
        sa.Column("referrer", sa.String(length=500), nullable=True),
        sa.Column("referrer_domain", sa.String(length=255), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("time_on_page", sa.Integer(), nullable=True),
        sa.Column("related_type", sa.String(length=50), nullable=True),
        sa.Column("related_id", sa.Integer(), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("ai_processed", sa.Boolean(), nullable=True),
        sa.Column("ai_insights", sa.JSON(), nullable=True),
        sa.Column("sentiment_score", sa.Float(), nullable=True),
        sa.Column("engagement_score", sa.Float(), nullable=True),
        sa.Column("experiment_id", sa.String(length=100), nullable=True),
        sa.Column("experiment_variant", sa.String(length=100), nullable=True),
        sa.Column("activity_metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_activities", schema=None) as batch_op:
        batch_op.create_index("idx_user_activities_page", ["page_url"], unique=False)
        batch_op.create_index(
            "idx_user_activities_related", ["related_type", "related_id"], unique=False
        )
        batch_op.create_index(
            "idx_user_activities_type_timestamp",
            ["activity_type", "timestamp"],
            unique=False,
        )
        batch_op.create_index(
            "idx_user_activities_user_session", ["user_id", "session_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_activities_activity_type"),
            ["activity_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_user_activities_session_id"), ["session_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_activities_timestamp"), ["timestamp"], unique=False
        )

    op.create_table(
        "user_roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("assigned_by", sa.Integer(), nullable=True),
        sa.Column("assigned_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "notification_type",
            sa.Enum(
                "system",
                "request",
                "task",
                "message",
                "achievement",
                "reminder",
                "alert",
                name="notificationtypeenum",
            ),
            nullable=False,
        ),
        sa.Column("recipient_id", sa.Integer(), nullable=False),
        sa.Column("recipient_type", sa.String(length=20), nullable=False),
        sa.Column("channels", sa.JSON(), nullable=False),
        sa.Column(
            "email_status",
            sa.Enum(
                "pending",
                "sent",
                "delivered",
                "read",
                "failed",
                "cancelled",
                name="notificationstatusenum",
            ),
            nullable=True,
        ),
        sa.Column(
            "app_status",
            sa.Enum(
                "pending",
                "sent",
                "delivered",
                "read",
                "failed",
                "cancelled",
                name="notificationstatusenum",
            ),
            nullable=True,
        ),
        sa.Column(
            "push_status",
            sa.Enum(
                "pending",
                "sent",
                "delivered",
                "read",
                "failed",
                "cancelled",
                name="notificationstatusenum",
            ),
            nullable=True,
        ),
        sa.Column(
            "priority",
            sa.Enum("low", "normal", "urgent", name="priorityenum"),
            nullable=False,
        ),
        sa.Column("is_read", sa.Boolean(), nullable=True),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.Column("related_type", sa.String(length=50), nullable=True),
        sa.Column("related_id", sa.Integer(), nullable=True),
        sa.Column("template_id", sa.Integer(), nullable=True),
        sa.Column("queue_id", sa.Integer(), nullable=True),
        sa.Column("delivery_channel", sa.String(length=20), nullable=True),
        sa.Column("final_subject", sa.String(length=200), nullable=True),
        sa.Column("final_title", sa.String(length=200), nullable=True),
        sa.Column("final_content", sa.Text(), nullable=True),
        sa.Column("extra_data", sa.JSON(), nullable=True),
        sa.Column("action_url", sa.String(length=500), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["queue_id"],
            ["notification_queue.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["notification_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index("idx_notifications_created", ["created_at"], unique=False)
        batch_op.create_index(
            "idx_notifications_recipient",
            ["recipient_id", "recipient_type"],
            unique=False,
        )
        batch_op.create_index(
            "idx_notifications_status",
            ["email_status", "app_status", "push_status"],
            unique=False,
        )
        batch_op.create_index(
            "idx_notifications_type", ["notification_type"], unique=False
        )

    op.create_table(
        "request_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=True),
        sa.Column("old_status", sa.String(length=50), nullable=True),
        sa.Column("new_status", sa.String(length=50), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["help_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("volunteer_id", sa.Integer(), nullable=False),
        sa.Column("skill_match_score", sa.Float(), nullable=True),
        sa.Column("location_match_score", sa.Float(), nullable=True),
        sa.Column("availability_match_score", sa.Float(), nullable=True),
        sa.Column("performance_match_score", sa.Float(), nullable=True),
        sa.Column("overall_match_score", sa.Float(), nullable=True),
        sa.Column("assigned_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("assigned_by", sa.String(length=50), nullable=True),
        sa.Column("volunteer_rating", sa.Integer(), nullable=True),
        sa.Column("volunteer_feedback", sa.Text(), nullable=True),
        sa.Column("admin_rating", sa.Integer(), nullable=True),
        sa.Column("admin_feedback", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["volunteer_id"],
            ["volunteers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_performance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("volunteer_id", sa.Integer(), nullable=False),
        sa.Column("time_taken_hours", sa.Float(), nullable=True),
        sa.Column("quality_rating", sa.Integer(), nullable=True),
        sa.Column("timeliness_rating", sa.Integer(), nullable=True),
        sa.Column("communication_rating", sa.Integer(), nullable=True),
        sa.Column("task_completed", sa.Boolean(), nullable=True),
        sa.Column("completion_notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["volunteer_id"],
            ["volunteers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_performance")
    op.drop_table("task_assignments")
    op.drop_table("request_logs")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index("idx_notifications_type")
        batch_op.drop_index("idx_notifications_status")
        batch_op.drop_index("idx_notifications_recipient")
        batch_op.drop_index("idx_notifications_created")

    op.drop_table("notifications")
    op.drop_table("user_roles")
    with op.batch_alter_table("user_activities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_activities_timestamp"))
        batch_op.drop_index(batch_op.f("ix_user_activities_session_id"))
        batch_op.drop_index(batch_op.f("ix_user_activities_activity_type"))
        batch_op.drop_index("idx_user_activities_user_session")
        batch_op.drop_index("idx_user_activities_type_timestamp")
        batch_op.drop_index("idx_user_activities_related")
        batch_op.drop_index("idx_user_activities_page")

    op.drop_table("user_activities")
    op.drop_table("two_factor_auth")
    op.drop_table("tasks")
    op.drop_table("role_permissions")
    op.drop_table("push_subscriptions")
    op.drop_table("notification_queue")
    op.drop_table("notification_preferences")
    with op.batch_alter_table("help_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_help_requests_status"))
        batch_op.drop_index(batch_op.f("ix_help_requests_source_channel"))
        batch_op.drop_index(batch_op.f("ix_help_requests_region"))
        batch_op.drop_index(batch_op.f("ix_help_requests_location_text"))
        batch_op.drop_index(batch_op.f("ix_help_requests_completed_at"))
        batch_op.drop_index(batch_op.f("ix_help_requests_city"))
        batch_op.drop_index(batch_op.f("ix_help_requests_assigned_volunteer_id"))

    op.drop_table("help_requests")
    op.drop_table("chat_participants")
    op.drop_table("chat_messages")
    op.drop_table("audit_logs")
    op.drop_table("admin_sessions")
    op.drop_table("admin_logs")
    with op.batch_alter_table("volunteers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_volunteers_location"))

    op.drop_table("volunteers")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_role"))

    op.drop_table("users")
    op.drop_table("user_behaviors")
    op.drop_table("success_stories")
    op.drop_table("roles")
    op.drop_table("requests")
    op.drop_table("permissions")
    op.drop_table("performance_metrics")
    op.drop_table("notification_templates")
    op.drop_table("feedbacks")
    op.drop_table("feedback")
    with op.batch_alter_table("failed_emails", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_failed_emails_recipient"))

    op.drop_table("failed_emails")
    op.drop_table("chatbot_conversations")
    op.drop_table("chat_rooms")
    op.drop_table("analytics_events")
    op.drop_table("admin_users")
    op.drop_table("achievements")
    # ### end Alembic commands ###
