"""Add phone to Volunteer

Revision ID: e20fdef9ec54
Revises: 3b3ea0b98404
Create Date: 2025-09-10 08:45:21.552870

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e20fdef9ec54"
down_revision = "3b3ea0b98404"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("help_requests", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column("email", sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column("phone", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("message", sa.Text(), nullable=False))
        batch_op.add_column(sa.Column("timestamp", sa.DateTime(), nullable=True))

    with op.batch_alter_table("volunteers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("phone", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("location", sa.String(length=100), nullable=True))
        batch_op.alter_column(
            "email",
            existing_type=sa.VARCHAR(length=120),
            type_=sa.String(length=100),
            existing_nullable=False,
        )
        batch_op.drop_index(batch_op.f("ix_volunteers_email"))
        batch_op.drop_column("status")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("volunteers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("status", sa.VARCHAR(length=50), nullable=True))
        batch_op.create_index(batch_op.f("ix_volunteers_email"), ["email"], unique=1)
        batch_op.alter_column(
            "email",
            existing_type=sa.String(length=100),
            type_=sa.VARCHAR(length=120),
            existing_nullable=False,
        )
        batch_op.drop_column("location")
        batch_op.drop_column("phone")

    with op.batch_alter_table("help_requests", schema=None) as batch_op:
        batch_op.drop_column("timestamp")
        batch_op.drop_column("message")
        batch_op.drop_column("phone")
        batch_op.drop_column("email")
        batch_op.drop_column("name")

    # ### end Alembic commands ###
