"""Add SuccessStory model

Revision ID: e52d3e8253fa
Revises: 11470b83273b
Create Date: 2025-09-10 09:07:35.621417

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e52d3e8253fa"
down_revision = "11470b83273b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "success_story",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("success_story")
    # ### end Alembic commands ###
