"""remove unintended schema drift operations

Revision ID: 4b921ad7568c
Revises: 782e7567009d
Create Date: 2026-03-16 19:23:31.569907

This revision intentionally does nothing.
The previous autogenerated body introduced unrelated schema churn and
SQLite rebuild risk across multiple tables.
"""

# revision identifiers, used by Alembic.
revision = "4b921ad7568c"
down_revision = "782e7567009d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    pass
