name: Auto-assign volunteers

on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to Stella
        uses: peter-evans/assign-issue@v2
        with:
          assignees: stellababy2004
